[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Serial
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

board_build.psram = enabled
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi
board_build.flash_mode = qio
board_build.f_flash = 80000000L

; Build flags
build_flags =
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=3
    -I include
    -DUSER_SETUP_LOADED
    -include include/tft_espi_setup.h
    -DUSE_UTF8_LONG_NAMES=1
    -DSDFAT_FILE_TYPE=1
    -DARDUINO_LOOP_STACK_SIZE=32768
    -DLOG_LEVEL=2

; Build type
build_type = debug

; Libraries
lib_deps =
    ; Display
    lvgl/lvgl@^8.3.11
    bodmer/TFT_eSPI@^2.5.43
    lovyan03/LovyanGFX@^1.1.12
    ; SD
    greiman/SdFat@^2.2.3

    ; NFC (RC522 example)
    miguelbalboa/MFRC522@^1.4.10

    ; Audio (optional)
    ; espressif/esp32-audioI2S
